apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-dep
  labels:
    app: jwt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-pod
  template:
    metadata:
      labels:
        app: pet-pod
    spec:
      containers:
        - name: jwt-cont
          image: jackredd/jwt:tagversion
          ports:
            - containerPort: 8080
              name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: pet-servicekb
spec:
  selector:
    app: pet-pod
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 8080
  type: LoadBalancer
